# Generated by Django 3.0.3 on 2020-02-18 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogdetailpage_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogdetailpage',
            old_name='blog_image',
            new_name='banner_image',
        ),
    ]
