# Generated by Django 3.0.3 on 2020-02-18 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_articlepage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogdetailpage',
            old_name='banner_image',
            new_name='blog_image',
        ),
    ]
