# Generated by Django 3.0.3 on 2020-02-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200218_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoblogpage',
            name='youtube_video_id',
            field=models.CharField(max_length=100),
        ),
    ]
